set number
set noswapfile
set mouse=a
set colorcolumn=80
set termguicolors
set completeopt=menuone,noinsert
filetype plugin indent on
set laststatus=2
set tabstop=4
set shiftwidth=4

colorscheme payne

inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <cr>    pumvisible() ? asyncomplete#close_popup() : "\<cr>"

let g:netrw_banner=0
let g:netrw_dirhistmax = 0
let g:asyncomplete_auto_completeopt = 0
let g:lsp_document_highlight_enabled = 0
let g:lsp_diagnostics_virtual_text_enabled = 0
let g:lsp_diagnostics_echo_cursor = 1
let g:lsp_diagnostics_echo_delay = 0
let g:lsp_settings_enable_suggestions = 0


function! MyTabLabel(n)
  let buflist = tabpagebuflist(a:n)
  let winnr = tabpagewinnr(a:n)
  let bufnr = buflist[winnr - 1]
  let name = bufname(bufnr)
  if name == ''
    let name = 'new'
  endif
  if getbufvar(bufnr, "&mod")
    let name = '+ ' .. name
  endif
  return name
endfunction


function! MyTabLine()
  let s = ''
  for i in range(tabpagenr('$'))
    let tab = i + 1
    if tab == tabpagenr()
      let s ..= '%#TabLineSel#'
      let s ..= '[ %{MyTabLabel(' .. (tab) .. ')} ]'
    else
      let s ..= '%#TabLine#'
      let s ..= '  %{MyTabLabel(' .. (tab) .. ')}  '
    endif
  
  endfor
  
  let s ..= '%#TabLineFill#%T'
  
  return s
endfunction


set tabline=%!MyTabLine()

