vim9script

set number
set noswapfile
set mouse=a
set colorcolumn=80
set termguicolors
set completeopt=menuone,noinsert
filetype plugin indent on
set laststatus=2
set tabstop=4
set shiftwidth=4
set wildmenu
set cursorline

colorscheme payne

g:netrw_banner = 0
g:netrw_dirhistmax = 0
g:vimcomplete_tab_enable = 1

def g:TabLabel(n: number): string
	var buflist = tabpagebuflist(n)
	var winnr = tabpagewinnr(n)
	var bufnr = buflist[winnr - 1]
	var name = bufname(bufnr)
	if name == ''
		name = '[No Name]'
	endif
	if getbufvar(bufnr, "&mod")
		name = '+ ' .. name
	endif
	return name
enddef

def g:TabLine(): string
	var s = ''
	for i in range(tabpagenr('$'))
		var tab = i + 1
		if tab == tabpagenr()
			s ..= '%#TabLineSel#'
		else
			s ..= '%#TabLine#'
		endif

		s ..= ' %{g:TabLabel(' .. (tab) .. ')} '
	endfor

	s ..= '%#TabLineFill#%T'

	return s
enddef

set tabline=%!g:TabLine()

packadd lsp
packadd vimcomplete


var servers: list<dict<any>> = []

if executable("pyright-langserver")
	add(servers, {
		name: 'pyright',
		filetype: 'python',
		path: exepath('pyright-langserver'),
		args: ['--stdio'],
		workspaceConfig: {
			python: {
				pythonPath: exepath('python'),
			}
		},
	})
endif

if executable("typescript-language-server")
	add(servers, {
		name: 'tsserver',
		filetype: ['javascript', 'typescript'],
		path: exepath('typescript-language-server'),
		args: ['--stdio']
	})
endif

call LspAddServer(servers)

var options = {
	completor: { noselect: false, noNewlineInCompletion: true }
}

autocmd VimEnter * g:VimCompleteOptionsSet(options)

