db_file            "~/.config/mpd/db"
music_directory    "~/music"

auto_update "yes"

playlist_directory "~/.config/mpd/playlists"
pid_file           "~/.config/mpd/pid"
state_file         "~/.local/state/mpd/state"

