[font]
size = 19

[font.normal]
family = "Fantasque Sans Mono"
style = "Regular"

[font.bold]
family = "Fantasque Sans Mono"
style = "Bold"

[font.bold_italic]
family = "Fantasque Sans Mono"
style = "Bold Italic"

[font.italic]
family = "Fantasque Sans Mono"
style = "Italic"

[colors.primary]
background = "#1f1f1f"
foreground = "#ffffff"

[colors.bright]
black = "#3f3f3f"
white = "#7f7f7f"

[colors.selection]
background = "#7f7f7f"
text = "#ffffff"

[cursor.style]
shape = "Underline"
blinking = "On"

[cursor]
blink_interval = 500
blink_timeout = 0

[window.padding]
x = 16
y = 16

