[font.normal]
family = "Commit Mono"

[font]
size = 16

[window.padding]
x = 16
y = 16

[cursor.style]
shape = "Underline"
blinking = "Always"

[cursor]
blink_interval = 500
unfocused_hollow = false

[colors.primary]
background = "#0f0f0f"
foreground = "#efefef"

[colors.normal]
black   = "#0f0f0f"
magenta = "#ef0f7f"
green   = "#7fef0f"
yellow  = "#ef7f0f"
blue    = "#0f7fef"
red     = "#0fef7f"
cyan    = "#7f0fef"
white   = "#efefef"

[colors.bright]
black   = "#0f0f0f"
magenta = "#ef0f7f"
green   = "#7fef0f"
yellow  = "#ef7f0f"
blue    = "#0f7fef"
red     = "#0fef7f"
cyan    = "#7f0fef"
white   = "#efefef"
