[font.normal]
family = "Fira Mono"

[font]
size = 16

# [window]
# opacity = 1.0

[window.padding]
x = 16
y = 16

[cursor.style]
shape = "Underline"
blinking = "Always"

[cursor]
blink_interval = 500
unfocused_hollow = false

[colors.primary]
background = '#1f1f1f'
foreground = '#efefef'

[colors.normal]
black   = '#efefef'
magenta = '#ef3f7f'
green   = '#7fef3f'
yellow  = '#ef7f3f'
blue    = '#3f7fef'
red     = '#efefef'
cyan    = '#3fef7f'
white   = '#efefef'

[colors.bright]
black   = '#3f3f3f'
magenta = '#ef3f7f'
green   = '#7fef3f'
yellow  = '#ef7f3f'
blue    = '#3f7fef'
red     = '#efefef'
cyan    = '#3fef7f'
white   = '#efefef'
