[font.normal]
family = "Fira Code"

[font]
size = 16

# [window]
# opacity = 1.0

[window.padding]
x = 16
y = 16

[cursor.style]
shape = "Underline"
blinking = "Always"

[cursor]
blink_interval = 500
unfocused_hollow = false

[colors.primary]
background = '#1f1f1f'
foreground = '#f1f1f1'

[colors.normal]
black   = '#ffffff'
red     = '#ffffff'
green   = '#ffffff'
yellow  = '#ffffff'
blue    = '#ffffff'
magenta = '#ffffff'
cyan    = '#ffffff'
white   = '#ffffff'

[colors.bright]
black   = '#3f3f3f'
red     = '#ffffff'
green   = '#ffffff'
yellow  = '#ffffff'
blue    = '#ffffff'
magenta = '#ffffff'
cyan    = '#ffffff'
white   = '#ffffff'
