[font]
size = 19

[font.normal]
family = "Fantasque Sans Mono"

[font.bold]
family = "Fantasque Sans Mono"
style ="Bold"

[font.italic]
family = "Fantasque Sans Mono"
style = "Italic"

[font.bold_italic]
family = "Fantasque Sans Mono"
style = "Bold Italic"

[colors.primary]
background = "#1f1f1f"
foreground = "#ffffff"

[colors.selection]
background = "#7f7f7f"
text = "#ffffff"

[cursor.style]
shape = "Underline"
blinking = "On"

[cursor]
blink_interval = 500
blink_timeout = 0
unfocused_hollow = false

[window]
opacity = 1

[window.padding]
x = 16
y = 16
