[font.normal]
family = "Fira Code"

[font]
size = 16

[window]
opacity = 0.5

[window.padding]
x = 16
y = 16

[cursor.style]
shape = "Underline"
blinking = "Always"

[cursor]
blink_interval = 500
unfocused_hollow = false

[colors.primary]
background = '#1f1f1f'
foreground = '#efefef'

[colors.normal]
black   = '#1f1f1f'
red     = '#efefef'
green   = '#7fef1f'
yellow  = '#ef7f3f'
blue    = '#efefef'
magenta = '#efefef'
cyan    = '#efefef'
white   = '#efefef'

[colors.bright]
black   = '#7f7f7f'
red     = '#efefef'
green   = '#7fef1f'
yellow  = '#ef7f3f'
blue    = '#3f7fef'
magenta = '#ef1f7f'
cyan    = '#efefef'
white   = '#efefef'
