[font.normal]
family = "Fira Mono"

[font]
size = 16

[window]
opacity = 0.5

[window.padding]
x = 16
y = 16

[cursor.style]
shape = "Underline"
blinking = "Always"

[cursor]
blink_interval = 500
unfocused_hollow = false

[colors.primary]
background = '#1f1f1f'
foreground = '#efefef'

[colors.normal]
black   = '#efefef'
red     = '#7f3fef'
green   = '#7fef3f'
yellow  = '#ef7f3f'
blue    = '#3f7fef'
magenta = '#ef3f7f'
white   = '#efefef'

[colors.bright]
black   = '#7f7f7f'
red     = '#7f3fef'
green   = '#7fef3f'
yellow  = '#ef7f3f'
blue    = '#3f7fef'
magenta = '#ef3f7f'
cyan    = '#3fef7f'
white   = '#efefef'
