[font]
size = 19

[font.normal]
family = "Fantasque Sans Mono"
style = "Regular"

[font.bold]
family = "Fantasque Sans Mono"
style = "Bold"

[font.bold_italic]
family = "Fantasque Sans Mono"
style = "Bold Italic"

[font.italic]
family = "Fantasque Sans Mono"
style = "Italic"

[colors.primary]
background = "#0f0f0f"
foreground = "#ffffff"

[cursor.style]
shape = "Underline"
blinking = "On"

[cursor]
blink_interval = 500
blink_timeout = 0

